<a href="https://colab.research.google.com/github/luckystarC/github-slideshow/blob/csci2033/%E2%80%9CProb3_Gaussian_Elimination_n_Back_Substitution_v1_6%E2%80%9D_Feiyu_Chen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Problem 3. Gaussian Elimination and Back Substitution**


Import required packages, and create matrix A and vector b

In [ ]:
import numpy as np
from numpy.linalg import norm
# fix  seed  for  reproducible  result. Please  do not  change  the  seed
rng = np.random.default_rng(20232033)
n = 300
A = rng.random((n,n))
b = rng.random((n,1))
#print("A = {}; \n b = {}".format(A,b))

**3.1 (1/4) Gaussian Elimination (Version 0)**



**Implement your own function: TODO**

In [ ]:
def gauss_elim_v0(A,b,print_flag=True):
  # check whether the calculation is valid
  assert A.shape[0] == A.shape[1],"A must be square!" # Make sure A is square
  assert A.shape[0] == b.shape[0],"Input dimension doesn't match!" # Make sure dimmension matches
  assert b.shape[1] == 1,"b is not a vector!" # Make sure b is a vector
  
  n = A.shape[0]  
  ###### YOUR CODE STARTS HERE ######
  U = np.concatenate((A,b), axis = 1) # Using A and b to generate the augmented matrix
  #   print your augmented matrix each step while it is modified
  #   you could symply use print(U) to print for each step
  if (print_flag):
    print(U)
    print("==============================================")
  for k in range(0,n-1):
    for j in range(k+1,n):
      l = U[j,k]/U[k,k]
      U[[j],:]=U[[j],:]-l*U[[k],:]
      if (print_flag):
        print(U)
        print("==============================================")
  ###################################
  return U

**Validate your result here using the example shown to you**

In [ ]:
A_example1 = np.array([[1,-1,1],[2,-1,3],[2,0,3]],dtype=np.float64)
b_example1 = np.array([[1],[4],[5]],dtype=np.float64)

U_example1 = gauss_elim_v0(A_example1,b_example1,True)

print(U_example1)

[[ 1. -1.  1.  1.]
 [ 2. -1.  3.  4.]
 [ 2.  0.  3.  5.]]
[[ 1. -1.  1.  1.]
 [ 0.  1.  1.  2.]
 [ 2.  0.  3.  5.]]
[[ 1. -1.  1.  1.]
 [ 0.  1.  1.  2.]
 [ 0.  2.  1.  3.]]
[[ 1. -1.  1.  1.]
 [ 0.  1.  1.  2.]
 [ 0.  0. -1. -1.]]
[[ 1. -1.  1.  1.]
 [ 0.  1.  1.  2.]
 [ 0.  0. -1. -1.]]


**3.2 (2/4) Back Substitution**

In [ ]:
# this function will check whether the matrix is in row echelon form
def check_row_echelon(U):
  eps = np.finfo(np.float32).eps # updated here!!! 
  # Previous version: eps = np.finfo(np.float64).eps
  test = np.tril(U,-1)
  #print(test) np.abs(test)
  return np.all(abs(test)<=eps)


**Implement your own function: TODO**

In [ ]:
def back_subs(U,print_flag = True):
  assert  check_row_echelon(U),"U must be in row echelon form"

  n = U.shape[0]
  x = np.zeros((n,1))
  ###### YOUR CODE STARTS HERE ######
  # print x[i] in the loop
  C = U[:,[-1]]
  D = U[:,:-1] 
  x[n-1]=C[n-1]/D[n-1,n-1]
  for i in range(n-1,-1,-1):
    tem=0
    for j in range(i+1,n):
      tem=tem+D[i,j]*x[j]
    x[i]=(C[i]-tem)/D[i,i]
    if(print_flag):
      print("R{}:x{}={}".format(i,i,x[i][0]))
      print(x[i])
    
  ###################################
  return x

Validate your result here using the example shown to you

In [ ]:
x_example1 = back_subs(U_example1,True)
print(x_example1)

R2:x2=1.0
[1.]
R1:x1=1.0
[1.]
R0:x0=1.0
[1.]
[[1.]
 [1.]
 [1.]]


**Call your own functions and validate your solutions (x1) by using relative distance ||Ax1 - b||/||A||: TODO**

In [ ]:
def my_solver_v0(A,b):
  
  U = gauss_elim_v0(A,b,False)
  ###### YOUR CODE STARTS HERE ######
  x = back_subs(U,False)
  ###################################
  return x

Validate your result here

In [ ]:
###### YOUR CODE STARTS HERE ######

x1= my_solver_v0(A,b)
dist =norm(np.matmul(A,x1)-b)/norm(A)
###################################
print("The relative error ||Ax1-b||/||A|| = {}".format(dist))

The relative error ||Ax1-b||/||A|| = 3.040481265980074e-12


**Call the numpy built-in function to solve the given questions (solution is x2), and compare it with your result using relative distance ||x1-x2||/||x2||: TODO**

In [ ]:
###### YOUR CODE STARTS HERE ######

x2 = np.linalg.solve(A,b)

dist = norm(x1-x2)/norm(x2)
# 

###################################
print("The relative distance ||x1-x2||/||x2|| = {}".format(dist))

The relative distance ||x1-x2||/||x2|| = 3.128314482595351e-11


**3.3 (1/4) Gaussian Elimination (Version 1)**

In [ ]:
A[0,0] = 0

**Implement your own function: TODO**

In [ ]:
def gauss_elim_v1(A,b,print_flag):
  # check whether the calculation is valid
  assert A.shape[0] == A.shape[1],"A must be square" # Make sure A is square
  assert A.shape[0] == b.shape[0],"Input dimension doesn't match" # Make sure dimmension matches
  assert b.shape[1] == 1,"b is not a vector" # Make sure b is a vector

  n = A.shape[0]  
  ###### YOUR CODE STARTS HERE ######
  U = np.concatenate((A,b), axis = 1) # Using A and b to generate the augmented matrix
  #   print your augmented matrix each step while it is modified
  #   you could symply use print(U) to print for each step
  if (print_flag):
    print(U)
    print("==============================================")
  for k in range(0,n-1):
    largest=0
    for i in range(k,n):
      if largest<np.abs(U[i,k]):
        largest=U[i,k]
    tem=U[[k],:]
    U[[k],:]=U[[i],:]
    U[[i],:]=tem
    for j in range(k+1,n):
      l = U[j,k]/U[k,k]
      U[[j],:]=U[[j],:]-l*U[[k],:]
      if (print_flag):
        print(U)
        print("==============================================")

  
  ###################################
  return U

In [ ]:
def my_solver_v1(A,b):
  U = gauss_elim_v1(A,b,False)
  ###### YOUR CODE STARTS HERE ######
  x = back_subs(U,False) # reuse your back_substitution function here
  ###################################

  return x

**Validate your result here using the example shown to you**

In [ ]:
A_example2 = np.array([[0,1,1],[2,6,4],[1,1,4]],dtype=np.float64)
b_example2 = np.array([[-1],[6],[9]],dtype=np.float64)

U_example2 = gauss_elim_v1(A_example2,b_example2,True)

print(U_example2)

[[ 0.  1.  1. -1.]
 [ 2.  6.  4.  6.]
 [ 1.  1.  4.  9.]]
[[  1.   1.   4.   9.]
 [  0.   4.  -4. -12.]
 [  0.   1.   1.  -1.]]
[[  1.   1.   4.   9.]
 [  0.   4.  -4. -12.]
 [  0.   1.   1.  -1.]]
[[ 1.  1.  4.  9.]
 [ 0.  1.  1. -1.]
 [ 0.  0. -8. -8.]]
[[ 1.  1.  4.  9.]
 [ 0.  1.  1. -1.]
 [ 0.  0. -8. -8.]]


**Call your own functions and validate your solutions (x1) by using relative distance ||Ax1 - b||/||A||: TODO**

In [ ]:
###### YOUR CODE STARTS HERE ######

x1 = my_solver_v1(A,b)
dist =norm(np.matmul(A,x1)-b)/norm(A)


###################################
print("The relative error ||Ax1-b||/||A|| = {}".format(dist))

The relative error ||Ax1-b||/||A|| = 4.928122502406297e-13


**Call the numpy built-in function to solve the given questions (solution is x2), and compare it with your result using relative distance ||x1-x2||/||x2||: TODO**

In [ ]:
###### YOUR CODE STARTS HERE ######

x2 = np.linalg.solve(A,b)
dist = norm(x1-x2)/norm(x2) 

###################################
print("The relative distance ||x1-x2||/||x2|| = {}".format(dist))

The relative distance ||x1-x2||/||x2|| = 2.1039651635182303e-12
