<a href="https://colab.research.google.com/github/luckystarC/github-slideshow/blob/csci2033/%E2%80%9CProb2_Matrix_Operations_v1_6%E2%80%9D_Feiyu_Chen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Problem 2. Matrix Operations**

In [ ]:
import numpy as np
# fix  seed  for  reproducible  result. Please  do not  change  the  seed
rng = np.random.default_rng(20232033)
A = rng.random((100 ,100))
B = rng.random((100 ,200))
C = rng.random((100 ,200))
D = rng.random((100 ,100))
u = rng.random((100 ,1))
v = rng.random((200 ,1))

**2.1 (0.5/4) Matrix Norms**

In [ ]:
###### YOUR CODE STARTS HERE ######
from numpy import linalg as LA
solution_1_a = LA.norm(A)

solution_1_b = LA.norm(B-C)

###################################
print(solution_1_a)
print()
print(solution_1_b)

57.74200003983731

57.70681874358965



**2.2 (0.5/4) Matrix Indexing**

In [ ]:
###### YOUR CODE STARTS HERE ######

solution_2_a = A[:50,:50]
solution_2_b = B[-30:,-25:]

###################################

print(solution_2_a)
print()
print(solution_2_b)

[[0.79333519 0.53234793 0.96829602 ... 0.71243022 0.78390693 0.68519395]
 [0.1763813  0.52431572 0.4796792  ... 0.02963053 0.17326307 0.32912718]
 [0.30262439 0.67864651 0.9236463  ... 0.53567316 0.10286055 0.39408668]
 ...
 [0.18484126 0.45302097 0.00197368 ... 0.2721152  0.03776999 0.95075046]
 [0.71609013 0.56005288 0.21113662 ... 0.11974251 0.81960495 0.22536406]
 [0.92617281 0.58412361 0.09277974 ... 0.70161782 0.41390725 0.40219501]]

[[0.05021279 0.69170802 0.88003647 0.86432376 0.1581059  0.60586831
  0.93232267 0.93305442 0.98757247 0.83542562 0.21714824 0.43499939
  0.48844572 0.00903565 0.06751099 0.60276914 0.86607322 0.53085673
  0.71437729 0.30859202 0.50501977 0.9842853  0.71678392 0.19249453
  0.2042969 ]
 [0.7436891  0.156883   0.3041397  0.68713496 0.91658955 0.93108287
  0.5383418  0.31713155 0.20115251 0.98290047 0.42729396 0.646887
  0.67630424 0.99037675 0.67131465 0.82544824 0.04484094 0.41576832
  0.73421817 0.17796458 0.05871652 0.63116432 0.07212953 0.88846977

**2.3 (0.5/4) Matrix Vector Multiplication**

In [ ]:
###### YOUR CODE STARTS HERE ######

solution_3_a =  np.matmul(A,u)

solution_3_b = np.matmul(C.T,u)

solution_3_c = np.matmul(B,v)

###################################
print(solution_3_a)
print()
print(solution_3_b)
print()
print(solution_3_c)

**2.4 (0.5/4) Matrix Matrix Multiplication**

In [ ]:
###### YOUR CODE STARTS HERE ######

solution_4_a = np.matmul(A,B)

solution_4_b = np.matmul(B,C.T)

solution_4_c = np.matmul(C.T,B)

solution_4_d = np.matmul(u,v.T)

###################################
print(solution_4_a)
print()
print(solution_4_b)
print()
print(solution_4_c)
print()
print(solution_4_d)

**2.5 (1/4) Matrix Power**

Implement your own function first:

In [ ]:
# Problem 2.5 (a)
def mat_pow(A,p):
  # check input
  assert A.shape[0] == A.shape[1], "Matrix input needs to be square!"
  assert p > 0, "p should be a positive integer!"
  assert isinstance(p, int), "p should have the data type of integer!"

  ###### YOUR CODE STARTS HERE ######
  Ap = A
  for i in range(1,p):
    Ap=np.matmul(Ap,A) 
  ###################################
  return Ap

Call your own function to solve the given questions:

In [ ]:
print("Problem 2.5(b)")
###### YOUR CODE STARTS HERE ######

solution_5_b_1 = np.matmul(mat_pow(A,6),mat_pow(A,8)) # put (A^6)(A^8)here

solution_5_b_2 = mat_pow(A,6+8) # put A^(6+8) here 

relative_dist_5_b = LA.norm(solution_5_b_1-solution_5_b_2)/LA.norm(solution_5_b_1)

###################################
print(solution_5_b_1)
print()
print(solution_5_b_2)
print()
print("relative distance between these two matrices is: ")
print(relative_dist_5_b)

In [ ]:
print("Problem 2.5(c)")
###### YOUR CODE STARTS HERE ######

solution_5_c_1 =mat_pow(mat_pow(A,6),8)  # put (A^6)^8 here

solution_5_c_2 =mat_pow(A,6*8)  # put A^(6*8) here 

relative_dist_5_c = LA.norm(solution_5_c_1-solution_5_c_2)/LA.norm(solution_5_c_1)

###################################
print(solution_5_c_1)
print()
print(solution_5_c_2)
print()
print("relative distance between these two matrices is: ")
print(relative_dist_5_c)
print()

**2.6 (1/4) Inverse and Transpose**

In [ ]:
print("Problem 2.6(a)")
###### YOUR CODE STARTS HERE ######

solution_6_a_1 = LA.inv(np.matmul(A,D)) # put (AD)^(-1) here

solution_6_a_2 = np.matmul(LA.inv(D),LA.inv(A)) # put (D^(-1))(A^(-1)) here 

relative_dist_6_a = LA.norm(solution_6_a_1-solution_6_a_2)/LA.norm(solution_6_a_1)

###################################
print(solution_6_a_1)
print()
print(solution_6_a_2)
print()
print("relative distance between these two matrices is: ")
print(relative_dist_6_a)
print()

In [ ]:
print("Problem 2.6(b)")
###### YOUR CODE STARTS HERE ######
solution_6_b_1 = LA.inv(A).T # put (A^(-1))^T here

solution_6_b_2 = LA.inv(A.T) # put (A^T)^(-1) here 

relative_dist_6_b = LA.norm(solution_6_b_1-solution_6_b_2)/LA.norm(solution_6_b_1)

###################################
print(solution_6_b_1)
print()
print(solution_6_b_2)
print()
print("relative distance between these two matrices is: ")
print(relative_dist_6_b)
print()

In [ ]:
print("Problem 2.6(c)")
###### YOUR CODE STARTS HERE ######

solution_6_c_1 = np.matmul(A,B).T # put (AB)^(T) here (Updated)

solution_6_c_2 = np.matmul(B.T,A.T) # put (B^T)(A^T) here 

relative_dist_6_c = LA.norm(solution_6_c_1-solution_6_c_2)/LA.norm(solution_6_c_1)

###################################
print(solution_6_c_1)
print()
print(solution_6_c_2)
print()
print("relative distance between these two matrices is: ")
print(relative_dist_6_c)